# Generated by Django 5.0.2 on 2024-02-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
