version: '3.8'

services:
  app:
    container_name: youshop_djangoapp
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/home/app
    env_file:
      - .env
    
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data