# Blue
[tool.blue]
extend-exclude = '(./venv|./*/migrations)'

# isort
[tool.isort]
profile = "black"
line_length = 79
known_third_party = ["django"]
skip = [
    "./src/project",
    "./src/*/migrations",
    "./src/manage.py"
]

# Tasks
[tool.taskipy.tasks]

lint = 'blue ./src --check --diff'
format = 'blue ./src && isort ./src'

check = 'mypy ./src'
check_strict = 'mypy ./src --strict --exclude manage.py'

pre_test = 'task lint && task check'
test = 'coverage run -m pytest ./src'
post_test = 'task format && coverage html'
