# Blue
[tool.blue]
extend-exclude = '(./venv|./*/migrations|./project)'

# isort
[tool.isort]
profile = "black"
line_length = 79
known_third_party = ["django"]
skip = [
    "./src/project",
    "./src/*/migrations",
    "./src/manage.py"
]

[tool.mypy]
ignore_missing_imports = true
exclude = ['migrations', 'tests']

# Tasks
[tool.taskipy.tasks]

lint = 'blue ./src --check --diff'
format = 'blue ./src && isort ./src'

check = 'mypy --config-file pyproject.toml ./src'
check_strict = 'mypy --config-file pyproject.toml ./src --strict '

pre_test = 'task lint && task check'
test = 'make tests'
post_test = 'task format'
